INSERT INTO escola.escola (id, nome, endereco, data_cadastro, situacao) VALUES(1, 'Escola Elizabeth de Freitas Magalhães', 'Rua 3', '2021-02-08 01:59:01.0', 'ATIVO');
INSERT INTO escola.escola (id, nome, endereco, data_cadastro, situacao) VALUES(2, 'Escola Gaspar Dutra', 'Av. Brasil', '2021-02-08 17:27:01.0', 'EXCLUIDO');
INSERT INTO escola.escola (id, nome, endereco, data_cadastro, situacao) VALUES(3, 'Escola Marechal Rondon', 'Av. rui', '2021-02-09 01:51:45.0', 'EXCLUIDO');
INSERT INTO escola.escola (id, nome, endereco, data_cadastro, situacao) VALUES(4, 'Escola Pindorama', 'Av. Brasil', '2021-02-09 09:24:15.0', 'ATIVO');

INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Fundamental', 'Matutino', 1, 1);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Fundamental', 'Matutino', 2, 2);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Fundamental', 'Matutino', 3, 3);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Fundamental', 'Matutino', 4, 5);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Fundamental', 'Matutino', 1, 14);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Fundamental', 'Matutino', 2, 15);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Fundamental', 'Matutino', 3, 16);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Fundamental', 'Matutino', 4, 17);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Fundamental', 'Matutino', 1, 18);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Fundamental', 'Matutino', 2, 19);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Fundamental', 'Matutino', 3, 20);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Fundamental', 'Matutino', 4, 21);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(4, 2020, 'Fundamental', 'Matutino', 1, 22);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(4, 2020, 'Fundamental', 'Matutino', 2, 23);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(4, 2020, 'Fundamental', 'Matutino', 3, 24);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(4, 2020, 'Fundamental', 'Matutino', 4, 25);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(6, 2020, 'Fundamental', 'Matutino', 1, 26);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(6, 2020, 'Fundamental', 'Matutino', 2, 27);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(6, 2020, 'Fundamental', 'Matutino', 3, 28);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(6, 2020, 'Fundamental', 'Matutino', 4, 29);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(7, 2020, 'Fundamental', 'Matutino', 1, 30);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(7, 2020, 'Fundamental', 'Matutino', 2, 31);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(7, 2020, 'Fundamental', 'Matutino', 3, 32);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(7, 2020, 'Fundamental', 'Matutino', 4, 33);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(8, 2020, 'Fundamental', 'Matutino', 1, 34);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(8, 2020, 'Fundamental', 'Matutino', 2, 35);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(8, 2020, 'Fundamental', 'Matutino', 3, 36);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(8, 2020, 'Fundamental', 'Matutino', 4, 37);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(9, 2020, 'Fundamental', 'Matutino', 1, 38);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(9, 2020, 'Fundamental', 'Matutino', 2, 39);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(9, 2020, 'Fundamental', 'Matutino', 3, 40);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(9, 2020, 'Fundamental', 'Matutino', 4, 41);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Médio', 'Matutino', 1, 42);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Médio', 'Matutino', 2, 43);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Médio', 'Matutino', 3, 44);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(1, 2020, 'Médio', 'Matutino', 4, 45);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Médio', 'Matutino', 1, 46);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Médio', 'Matutino', 2, 47);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Médio', 'Matutino', 3, 48);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(2, 2020, 'Médio', 'Matutino', 4, 49);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Médio', 'Matutino', 1, 50);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Médio', 'Matutino', 2, 51);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Médio', 'Matutino', 3, 52);
INSERT INTO escola.turma (serie, ano, nivel_ensino, turno, escola_id, id) VALUES(3, 2020, 'Médio', 'Matutino', 4, 53);
